### ISSUE TITLE
training batch size

### ISSUE THREAD

**Issue by twangnh** [Epiphqny/SOLOv2#11]
Hi, here the config uses batch size 4 for training, so in total 32 for 8-gpu machine, but batch size in solov2 paper is 16, I'm wondering if bs=16 has lower performance, or similar with bs=32 and you just want to training faster? Thanks !

**Comment by Epiphqny** [comment]
Just want to training faster.

**Comment by twangnh** [comment]
so may be bs=16 could have better performance

**Comment by Epiphqny** [comment]
You can try and test.

**Comment by twangnh** [comment]
thanks
