### ISSUE TITLE
Res50 result

### ISSUE THREAD

**Issue by twangnh** [Epiphqny/SOLOv2#12]
Hi! thanks for your implementation, I tried to change the backbone to resnet50 with other settings not change, but only get 37.0 AP on val 2017 set, I'm wondering if you also encounter the problem, so only res101 model is released ?

**Comment by Epiphqny** [comment]
@twangnh I only tried resnet101, and the AP on test-dev is higher than val, you can test your model on test-dev to see the result. Also, the result of solov1_r50 is 35.8  in https://github.com/WXinlong/SOLO , so the result of 37.0 is higher than the solov1, i think it is normal.

**Comment by twangnh** [comment]
thanks for reply, yes there is large improvement over solov1, but the solov2 paper report 37.8 val AP with resnet50, so there is a ~0.8 gap between that

**Comment by Epiphqny** [comment]
I have not tested on resnet50 and have no extra gpu to run the experiment, so can not answer that. I will update when finished.
