### ISSUE TITLE
question about test-dev result

### ISSUE THREAD

**Issue by twangnh** [Epiphqny/SOLOv2#15]
Hi Yuqing, I upload the result of the pertained model to test-dev of 2019 server (https://competitions.codalab.org/competitions/20796#participate), but only got 39.3
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.393
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.606
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.423
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.168
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.569
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.324
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.503
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.526
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.282
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.583
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.727

I'm wondering if you can share the server you used for test-dev evaluation? because I cannot find test-dev 2017 version server

**Comment by Epiphqny** [comment]
hi @twangnh , the AP is correct. If you modify the mask of different level to the same size during training, it will reach 39.5AP, please refer to https://github.com/Epiphqny/SOLOv2/issues/7
