### ISSUE TITLE
How can I train with --validate?

### ISSUE THREAD

**Issue by JiangWeiHn** [Epiphqny/SOLOv2#20]
I want train my data with validation.so I use the --validate.I got the error：
bboxes.shape[0]  is 'tuple',has no attribute ‘shape’, how can I improve the code to train with validate?please help me

**Comment by kobewangSky** [comment]
I can not use test.py  same problem@@

**Comment by YuqingWang1029** [comment]
@JiangWeiHn @kobewangSky The inference code follows the same way as SOLOv1 https://github.com/WXinlong/SOLO, which use test_ins.py file to test, it seems that it does not support validation during training. if you really need the feature, please refer to the source code of mmdetection.

**Comment by JiangWeiHn** [comment]
ok  thanks
