### ISSUE TITLE
mmdetection框架不能转成tensorrt？

### ISSUE THREAD

**Issue by yutao007** [Epiphqny/SOLOv2#21]

**Comment by yutao007** [comment]
感谢作者的算法开源，但是最近测试时候，就发现无法转移成tensorrt7框架下，如果实验室跑数据还行，如果想要实践工程就难了。各种op  tensorrt7都不支持

**Comment by YuqingWang1029** [comment]
@yutao007 Please refer to https://github.com/open-mmlab/mmdetection/issues/1822, it seems some ops are not supported now.

**Comment by yutao007** [comment]
是的，感谢作者，我现在就是在转换的时候遇到问题了。mmdetection框架目前无法解决。
