### ISSUE TITLE
why I cannot get result when I use the demo?

### ISSUE THREAD

**Issue by JiangWeiHn** [Epiphqny/SOLOv2#4]
I have download the solov2.pth file and debug the webcam_demo,the model and the data have value.but the result is None.What's the problem? i need you help 
![Screenshot from 2020-04-11 17-06-55](https://user-images.githubusercontent.com/24561984/79039927-4dd33200-7c17-11ea-9d4b-739d057d9a7c.png)

**Comment by Epiphqny** [comment]
@JiangWeiHn, i only used the test_ins.py and haven't run the demo file from the original solov1 repo, you can test the same file in solov1 using his checkpoint and see if it works. If it only fails in my repo, i will check it.

**Comment by JiangWeiHn** [comment]
I run the solov1 model.there is no problem.then I debug the solov2 carefully,and find  in the function of get_seg_single, seg_preds is very small, the max of this tensor is 0.0034. so the keep.sum()==0,return None.maybe the weights problem?  I guss.

**Comment by Epiphqny** [comment]
@JiangWeiHn I think you could first use the test_ins.py file to evaluate the model and check if the weights have problem.

**Comment by JiangWeiHn** [comment]
好的 我试试

**Comment by Epiphqny** [comment]
@JiangWeiHn Please let me know if the evaluation has any problem.

**Comment by JiangWeiHn** [comment]
![Screenshot from 2020-04-14 10-35-04](https://user-images.githubusercontent.com/24561984/79180364-548ebe80-7e3c-11ea-9310-33af7851f96b.png)
 I have run the  test_ins.py and test_ins_vis.py,It's got the same result,I don't know why

**Comment by Epiphqny** [comment]
@JiangWeiHn Is your code the latest? Please pull the latest code and test again. I will let another people test the model and check if it works.

**Comment by JiangWeiHn** [comment]
I have down another weights ,and it works.

**Comment by JiangWeiHn** [comment]
the universea/SOLOv2's weights work.

**Comment by Epiphqny** [comment]
Hi@JiangWeiHn , i found the problem, it's my fault. The config file is not consist with the model. I have uploaded the new config with only 4 conv heads, please test and check.

**Comment by JiangWeiHn** [comment]
OK，it works.
