### ISSUE TITLE
training stuck doesn't print any log

### ISSUE THREAD

**Issue by luohao123** [Epiphqny/SOLOv2#5]
it stucked doesn't print any thing

**Comment by luohao123** [comment]
also, how to make it support resnet50 as backbone to train?

**Comment by luohao123** [comment]
I know how to train resnet50, how to make it log out every epoch loss?

**Comment by Epiphqny** [comment]
@luohao123 The training of the model might cost large resources, you could try a smaller model or decrease the batchsize. And sometimes it is training even no log, please check the work_dir of the config file to see if there is any .log or .json file, it might has logs.

**Comment by jinfagang** [comment]
how to print it to terminal

**Comment by Epiphqny** [comment]
In the default setting, it should print to terminal. If it didn't, perhaps
it is the resource and mmdet problem.

JinTian <notifications@github.com> 于2020年4月16日周四 下午12:45写道：

**Comment by jinfagang** [comment]
default not
