### ISSUE TITLE
Question about mask loss

### ISSUE THREAD

**Issue by qin2294096** [Epiphqny/SOLOv2#7]
Thanks for your work!

https://github.com/Epiphqny/SOLOv2/blob/master/mmdet/models/anchor_heads/solov2_head.py#L373
https://github.com/Epiphqny/SOLOv2/blob/master/mmdet/models/anchor_heads/solov2_head.py#L200
I have noticed that, in training, the gt masks and mask predictions are downsampled to smaller scales(1/4, 1/4, 1/8, 1/16, 1/16 from p2~p6). And these downsampled masks are used to compute loss.

However, solov2 can predict masks on 1/4 scale directly, so my question is, why not compute loss with gt masks on 1/4 scale like yolact? Thank you.
（为什么这里不像yolact那样，直接用1/4大小的gt mask去计算损失？）

**Comment by Epiphqny** [comment]
@qin2294096 I have implemented the 1/4 scale mask loss before, the result is about 0.2 point higher than current version, because the code is similar, i didn't update.
